stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: camera-proxy
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA}

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind

containerization:
  stage: containerization
  only:
    - master
  tags:
    - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    # Building
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    # Pushing
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}
    # cleanup
    - docker image rm ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE_TAGGED}

deployment:
  stage: deployment
  only:
    - master
  tags:
    - dind
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
