apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-proxy
  template:
    metadata:
      labels:
        app: camera-proxy
    spec:
      containers:
      - name: camera-proxy
        image: moreillon/camera-proxy
        ports:
        - containerPort: 80
        env:
        - name: GROUP_AUTHORIZATION_URL
          value: https://api.groups.maximemoreillon.com/v3/users/self/groups
        - name: AUTHORIZED_GROUPS
          value: 0035cdb9-838a-4cdd-8ab5-61dafdf569d8
        envFrom:
        - secretRef:
           name: environment-variables
---
apiVersion: v1
kind: Service
metadata:
  name: camera-proxy
spec:
  ports:
  - port: 80
    nodePort: 30007
  selector:
    app: camera-proxy
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: camera-proxy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # This is necessary, no idea why
spec:
  tls:
  - hosts:
    - api.cameras.home.maximemoreillon.com
    secretName: camera-proxy
  rules:
  - host: api.cameras.home.maximemoreillon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: camera-proxy
          servicePort: 80
